## Importing the libraries


In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict


In [2]:
Data=pd.read_csv(r"C:\Users\Admin\Downloads\Heart_Dis.csv")

In [3]:
Data.head(1)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   

   ca  thal  target  
0   2     3       0

In [4]:
Data.shape

(1025, 14)

In [5]:
Data.isnull().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [6]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [7]:
Data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [8]:
Data['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

In [9]:
#Data is imbalance because count of target class is not balance count of 1 is larger than count of 0

In [10]:
Data.corr()

age       sex        cp  trestbps      chol       fbs  \
age       1.000000 -0.103240 -0.071966  0.271121  0.219823  0.121243   
sex      -0.103240  1.000000 -0.041119 -0.078974 -0.198258  0.027200   
cp       -0.071966 -0.041119  1.000000  0.038177 -0.081641  0.079294   
trestbps  0.271121 -0.078974  0.038177  1.000000  0.127977  0.181767   
chol      0.219823 -0.198258 -0.081641  0.127977  1.000000  0.026917   
fbs       0.121243  0.027200  0.079294  0.181767  0.026917  1.000000   
restecg  -0.132696 -0.055117  0.043581 -0.123794 -0.147410 -0.104051   
thalach  -0.390227 -0.049365  0.306839 -0.039264 -0.021772 -0.008866   
exang     0.088163  0.139157 -0.401513  0.061197  0.067382  0.049261   
oldpeak   0.208137  0.084687 -0.174733  0.187434  0.064880  0.010859   
slope    -0.169105 -0.026666  0.131633 -0.120445 -0.014248 -0.061902   
ca        0.271551  0.111729 -0.176206  0.104554  0.074259  0.137156   
thal      0.072297  0.198424 -0.163341  0.059276  0.100244 -0.042177   
target   -0.229324 -0.279501  0.434854 -0.138772 -0.099966 -0.041164   

           restecg   thalach     exang   oldpeak     slope        ca  \
age      -0.132696 -0.390227  0.088163  0.208137 -0.169105  0.271551   
sex      -0.055117 -0.049365  0.139157  0.084687 -0.026666  0.111729   
cp        0.043581  0.306839 -0.401513 -0.174733  0.131633 -0.176206   
trestbps -0.123794 -0.039264  0.061197  0.187434 -0.120445  0.104554   
chol     -0.147410 -0.021772  0.067382  0.064880 -0.014248  0.074259   
fbs      -0.104051 -0.008866  0.049261  0.010859 -0.061902  0.137156   
restecg   1.000000  0.048411 -0.065606 -0.050114  0.086086 -0.078072   
thalach   0.048411  1.000000 -0.380281 -0.349796  0.395308 -0.207888   
exang    -0.065606 -0.380281  1.000000  0.310844 -0.267335  0.107849   
oldpeak  -0.050114 -0.349796  0.310844  1.000000 -0.575189  0.221816   
slope     0.086086  0.395308 -0.267335 -0.575189  1.000000 -0.073440   
ca       -0.078072 -0.207888  0.107849  0.221816 -0.073440  1.000000   
thal     -0.020504 -0.098068  0.197201  0.202672 -0.094090  0.149014   
target    0.134468  0.422895 -0.438029 -0.438441  0.345512 -0.382085   

              thal    target  
age       0.072297 -0.229324  
sex       0.198424 -0.279501  
cp       -0.163341  0.434854  
trestbps  0.059276 -0.138772  
chol      0.100244 -0.099966  
fbs      -0.042177 -0.041164  
restecg  -0.020504  0.134468  
thalach  -0.098068  0.422895  
exang     0.197201 -0.438029  
oldpeak   0.202672 -0.438441  
slope    -0.094090  0.345512  
ca        0.149014 -0.382085  
thal      1.000000 -0.337838  
target   -0.337838  1.000000

In [11]:
#slice the data 

In [12]:
x=Data.iloc[:,:-1].values
y=Data.iloc[:,-1].values

In [13]:
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [14]:
y

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [15]:
#Balance the Data using Smote Technique

In [17]:
from imblearn.over_sampling import SMOTE
s=SMOTE()
x_data,y_data=s.fit_resample(x,y)

In [18]:
from collections import Counter

In [19]:
Counter(y_data)

Counter({0: 526, 1: 526})

In [21]:
# Feature Scaling by StandardScaler()


In [22]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_ss=ss.fit_transform(x_data)
x_ss

array([[-0.27354459,  0.65696053, -0.89958453, ...,  0.99813726,
         1.2065841 ,  1.07417166],
       [-0.16251027,  0.65696053, -0.89958453, ..., -2.24828005,
        -0.74412915,  1.07417166],
       [ 1.72507325,  0.65696053, -0.89958453, ..., -2.24828005,
        -0.74412915,  1.07417166],
       ...,
       [ 0.1254584 , -0.75533698, -0.21029899, ..., -0.6250714 ,
        -0.74412915,  1.07417166],
       [-1.29758037,  0.65696053, -0.89958453, ..., -0.6250714 ,
        -0.36505464, -1.51729638],
       [-0.71768189,  0.65696053, -0.89958453, ...,  0.99813726,
         1.2065841 ,  1.07417166]])

In [23]:
y_ss=y_data

# slpit data into train and test


In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_ss,y_ss,test_size=0.2,random_state=100)

In [25]:
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 423, 1: 418})
Counter({1: 108, 0: 103})


# Cross validation technique 


In [26]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=11,shuffle=True)
kf.get_n_splits(x)
print(kf)

KFold(n_splits=5, random_state=11, shuffle=True)


In [27]:
from sklearn.linear_model import LogisticRegression
LogisticRegression
l1=LogisticRegression()


In [28]:
l1.fit(x_train,y_train)
y_pred=l1.predict(x_test)
print(y_pred)

[0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 1 1
 1 1 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0
 1 1 0 0 0 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0
 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0
 0 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 1]


In [32]:
for train_data,test_data in kf.split(x):
    x_train,x_test=x_ss[train_data],x_ss[test_data]
    y_train,y_test=y_ss[train_data],y_ss[test_data]
    scores=cross_val_score(l1,x_train,y_train,cv=kf)
    y_pred=cross_val_predict(l1,x_test,y_test)
    print("Checking y_test Balancing.......:",Counter(y_test))
    print(y_pred)
    print(scores)
    print(np.mean(scores)*100)
    
    

Checking y_test Balancing.......: Counter({1: 108, 0: 97})
[0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 1
 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 1 0
 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1
 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 0
 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 0 0
 1 1 1 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1 0 0]
[0.82926829 0.82317073 0.85365854 0.84146341 0.85365854]
84.02439024390243
Checking y_test Balancing.......: Counter({0: 107, 1: 98})
[0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 0 1
 0 0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0
 0 1 0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1
 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1
 1 0 0 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0
 1 1 0 0 1 0 1 

In [35]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5,shuffle=True, random_state=21)
skf.get_n_splits(x_ss,y_ss)

for train_data,test_data in skf.split(x_ss,y_ss):
    x_train,x_test=x_ss[train_data],x_ss[test_data]
    y_train,y_test=y_ss[train_data],y_ss[test_data]
    scores=cross_val_score(l1,x_train,y_train,cv=kf)
    y_pred=cross_val_predict(l1,x_test,y_test)
    print("Checking y_test Balancing.......:",Counter(y_test))
    print(y_pred)
    print(scores)
    print(np.mean(scores)*100)    

Checking y_test Balancing.......: Counter({0: 106, 1: 105})
[1 0 0 1 1 1 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1
 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0
 0 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0
 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1
 0 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1
 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0]
[0.84023669 0.86904762 0.82142857 0.83333333 0.82738095]
83.82854325162018
Checking y_test Balancing.......: Counter({1: 106, 0: 105})
[0 0 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 1 1
 0 0 1 0 1 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 0
 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0
 0 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1
 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 0
 

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from collections import Counter
l=LogisticRegression()
r= RandomForestClassifier()

In [40]:
print(l.fit(x_train,y_train))
print(r.fit(x_train,y_train))

LogisticRegression()
RandomForestClassifier()


In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
for clf in (l,r):
    y_pred = clf.predict(x_test)
    print(
        clf.__class__.__name__,
        '\n',
        'Accuracy score: ',accuracy_score(y_test, y_pred), '\n',
        'Precision score: ',precision_score(y_test, y_pred, zero_division = 1), '\n',
        'Recall score: ',recall_score(y_test, y_pred, zero_division = 1), '\n',
        'F1 score: ',f1_score(y_test, y_pred, zero_division = 1), '\n',
        'ROC AUC score: ',roc_auc_score(y_test, y_pred), '\n', 

    )

LogisticRegression 
 Accuracy score:  0.8476190476190476 
 Precision score:  0.811965811965812 
 Recall score:  0.9047619047619048 
 F1 score:  0.8558558558558558 
 ROC AUC score:  0.8476190476190475 

RandomForestClassifier 
 Accuracy score:  0.9857142857142858 
 Precision score:  1.0 
 Recall score:  0.9714285714285714 
 F1 score:  0.9855072463768115 
 ROC AUC score:  0.9857142857142858 

