In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score 


In [2]:
Data=pd.read_csv(r"C:\Users\Admin\Downloads\Heart_Dis.csv")

In [3]:
Data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [4]:
Data['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

In [5]:
#Data is imbalance because count of target class is not balance count of 1 is larger than count of 0

In [6]:
x=Data.iloc[:,:-1].values
y=Data.iloc[:,-1].values

In [7]:
#Balance the Data using Smote Technique

In [8]:
from imblearn.over_sampling import SMOTE
S=SMOTE()
x_data,y_data=S.fit_resample(x,y)

In [9]:
from collections import Counter

In [10]:
Counter(y_data)

Counter({0: 526, 1: 526})

In [11]:
# Feature Scaling by StandardScaler()


In [12]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_ss=ss.fit_transform(x_data)
x_ss

array([[-0.27342645,  0.6551965 , -0.90695585, ...,  1.0056297 ,
         1.2021029 ,  1.06865632],
       [-0.16293608,  0.6551965 , -0.90695585, ..., -2.23848753,
        -0.74267929,  1.06865632],
       [ 1.71540016,  0.6551965 , -0.90695585, ..., -2.23848753,
        -0.74267929,  1.06865632],
       ...,
       [-0.32886536,  0.6551965 , -0.05513771, ...,  0.29633456,
         0.77689491, -0.32843794],
       [-0.93636866,  0.6551965 , -0.90695585, ..., -0.61642892,
         1.2021029 ,  1.06865632],
       [ 0.83147722,  0.6551965 ,  0.06703852, ..., -0.61642892,
         0.22971181,  1.06865632]])

In [13]:
y_ss=y_data

# slpit data into train and test


In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_ss,y_ss,test_size=0.2,random_state=100)

In [15]:
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 423, 1: 418})
Counter({1: 108, 0: 103})


In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from collections import Counter
l=LogisticRegression()
k=KNeighborsClassifier()
r= RandomForestClassifier()

In [17]:
print(l.fit(x_train,y_train))
print(k.fit(x_train,y_train))
print(r.fit(x_train,y_train))

LogisticRegression()
KNeighborsClassifier()
RandomForestClassifier()


In [18]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
for clf in (l,k,r):
    y_pred = clf.predict(x_test)
    print(
        clf.__class__.__name__,
        '\n',
        'Accuracy score: ',accuracy_score(y_test, y_pred)*100, '\n',
        'Precision score: ',precision_score(y_test, y_pred, zero_division = 1)*100, '\n',
        'Recall score: ',recall_score(y_test, y_pred, zero_division = 1)*100, '\n',
        'F1 score: ',f1_score(y_test, y_pred, zero_division = 1)*100, '\n',
        'ROC AUC score: ',roc_auc_score(y_test, y_pred)*100, '\n', 

    )

LogisticRegression 
 Accuracy score:  86.25592417061611 
 Precision score:  83.76068376068376 
 Recall score:  90.74074074074075 
 F1 score:  87.1111111111111 
 ROC AUC score:  86.14706939949659 

KNeighborsClassifier 
 Accuracy score:  81.99052132701422 
 Precision score:  88.88888888888889 
 Recall score:  74.07407407407408 
 F1 score:  80.8080808080808 
 ROC AUC score:  82.1826681049982 

RandomForestClassifier 
 Accuracy score:  98.5781990521327 
 Precision score:  100.0 
 Recall score:  97.22222222222221 
 F1 score:  98.59154929577464 
 ROC AUC score:  98.61111111111111 



# VotingClassifier Ensemble Techniques

In [19]:
from sklearn.ensemble import VotingClassifier
V1=VotingClassifier(estimators=[("LogisticRegression",l),("KNeighborsClassifier",k),("RandomForestClassifier",r)])
V1.fit(x_train,y_train)


VotingClassifier(estimators=[('LogisticRegression', LogisticRegression()),
                             ('KNeighborsClassifier', KNeighborsClassifier()),
                             ('RandomForestClassifier',
                              RandomForestClassifier())])

In [20]:
y_predV=V1.predict(x_test)
y_predV

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [21]:
aa=V1.score(x_test,y_test)*100
print("VotingClassifier accuracy",aa)

VotingClassifier accuracy 91.9431279620853


In [22]:
aa2=V1.score(x_train,y_train)*100
print("VotingClassifier accuracy",aa)

VotingClassifier accuracy 91.9431279620853


# Bagging with LogisticRegression

In [23]:
from sklearn.ensemble import BaggingClassifier
BG=BaggingClassifier(base_estimator=l,n_estimators=5,random_state=11)
BG.fit(x_train,y_train)

BaggingClassifier(base_estimator=LogisticRegression(), n_estimators=5,
                  random_state=11)

In [24]:
y_predbg=BG.predict(x_test)
y_predbg

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [25]:
bg_score=BG.score(x_test,y_test)*100
bg_score

85.30805687203792

In [26]:
bg_score=BG.score(x_train,y_train)*100
bg_score

85.85017835909632

# bagging with RandomForestClassifier

In [27]:
from sklearn.ensemble import BaggingClassifier
BG2=BaggingClassifier(base_estimator=r,n_estimators=5,random_state=11)
BG2.fit(x_train,y_train)
y_predbg=BG2.predict(x_test)
bg_score=BG2.score(x_test,y_test)*100
print(y_predbg)
print(bg_score)


[0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 0
 1 1 0 1 0 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 1 1
 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0
 1 0 0 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1
 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0
 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 1]
98.10426540284361


In [30]:
#Using Ensemble technique my accuracy increase in VotingClassifier 